import { DESCRIPTION, FULL_WEBSITE_URL, GITHUB_REPO_URL, TITLE } from '@/constants';

export const PH_TAGLINE = 'Turn YouTube subscriptions into a personal newsletter';

export const PH_DESCRIPTION =
  'Turn YouTube subscriptions into a personal newsletter. Every channel becomes a triaged inbox of readable videos. Two summaries plus a full article for every video. Search semantically, pin notes, read in your language. Built for depth, not distraction.';

export const PH_TOPICS = [
  'Productivity',
  'Reading',
  'Artificial Intelligence',
  'Open Source',
  'Education',
];

export const PH_FIRST_COMMENT = `Hi Product Hunt 👋

I'm Liren, the maker of ${TITLE}.

I built ${TITLE} because I kept saving long YouTube videos for "later" and rarely returning. The feed is engineered to hold attention; nothing about it helps me sit with an idea.

${TITLE} turns the channels you follow into a triaged inbox of readable videos. For every video you add, you get a one-line headline, a paragraph for skimming, and a full-length article when you want to sit with the ideas — a 20-minute video becomes a five-minute read you can come back to.

A few things that make it different:

• Inbox model — star, save for later, archive, mark unread; the same muscle memory as your email, applied to videos.
• Article-first reading — generated by an LLM, not stitched-together captions, and translatable in place.
• Semantic search across every channel you follow — your subscriptions become a personal archive of ideas, not a feed you scroll past.
• Notes and highlights pinned alongside the article, timestamped back to the source.
• Source available under the Elastic License 2.0 — self-host the full product on your own infrastructure with your own AI keys.

Free during the beta. Works with YouTube and Bilibili. Would love your honest feedback.

Stop scrolling. Start reading.

— Liren
${FULL_WEBSITE_URL}
${GITHUB_REPO_URL}`;

export const PH_LINKS = {
  website: FULL_WEBSITE_URL,
  github: GITHUB_REPO_URL,
};

export const HERO_HEADLINE = 'Read YouTube videos';
export const HERO_SUBTITLE = DESCRIPTION;

export const FEATURES_HEADLINE = 'Built for depth, not distraction';
export const FEATURES_SUBHEADLINE =
  'A quiet reading space for the videos worth your attention, and the thinking they deserve.';

export const CTA_HEADLINE = 'Stop scrolling. Start reading.';
export const CTA_SUBHEADLINE =
  'The feed is engineered to hold your attention. ReadTube is built to return it.';

export interface FeatureCopy {
  key: string;
  title: string;
  description: string;
}

export const FEATURES: readonly FeatureCopy[] = [
  {
    key: 'inbox',
    title: 'Read your subscriptions like a newsletter inbox',
    description:
      'Every channel you follow becomes a triaged inbox of readable videos. Star, save for later, archive, mark unread — the same muscle memory as your email, applied to videos you would have otherwise watched on autoplay.',
  },
  {
    key: 'article',
    title: 'Two summaries and a full-length article for every video',
    description:
      'A one-line headline and a paragraph for skimming, then a full narrative rewrite when you want to sit with the ideas. A 20-minute video becomes a five-minute read you can come back to.',
  },
  {
    key: 'translation',
    title: 'Read in your language',
    description:
      'Generate summaries and articles in the language you actually think in. Pick from the language menu and the entire piece switches in place — translated by the same model that wrote it, not a separate machine-translation pass.',
  },
  {
    key: 'search',
    title: 'Search the way you think',
    description:
      'Semantic search across every channel you follow. Your subscriptions become a personal archive of ideas, not a feed you scroll past.',
  },
  {
    key: 'notes',
    title: 'Notes and highlights you can sit with',
    description:
      'Pin timestamped notes alongside the article. Your thinking lives next to the source — not in a second app you forget to open.',
  },
];
