export const MAIN_COLOR = '#515ada';
export const MINOR_COLOR = '#76ABDF';

export const TITLE = 'ReadTube';
export const DESCRIPTION =
  'Turn YouTube subscriptions into a personal newsletter. Reclaim focus in a world engineered for distraction.';
export const DOMAIN = 'read.tube';
export const DOMAIN_URL = `https://${DOMAIN}`;
export const CONTACT_EMAIL = `contact@${DOMAIN}`;

// https://vercel.com/liren/~/ai-gateway/models
// google/gemini-3.1-flash-lite-preview: $0.25 / $1.5 - tend to summarize for article too
// openai/gpt-5.4-nano: $0.20 / $1.25 - not much formatting for article
// openai/gpt-5.4-mini: $0.74 / $4.5
// openai/gpt-5.4: $2.5 / $15 - too expensive
// anthropic/claude-haiku-4.5: $1 / $5 - slow
export const DEFAULT_AI_MODEL = 'openai/gpt-5.4-mini';

/**
 * Model for semantic embeddings. 1536 native dims matches the pgvector
 * column in the schema. We use OpenAI for embeddings even though
 * generation (summaries, articles, Ask-my-inbox answers) uses Google
 * Gemini — the Vercel AI Gateway routes them independently by provider
 * prefix, and no 1536-dim Google embedding model is available through
 * the gateway as a plain string identifier today. If you swap to a
 * model with a different output size, bump EMBEDDING_PROMPT_VERSION
 * AND alter the pgvector column + HNSW index together.
 *
 * https://developers.openai.com/api/docs/pricing
 * $0.02
 */
export const DEFAULT_EMBEDDING_MODEL = 'openai/text-embedding-3-small';

/**
 * Maximum attempts (initial + retries) for `streamText` calls in
 * generation steps when nothing has been streamed to the client yet.
 * Once any delta has been emitted, retrying would re-stream content
 * the client already received, so the retry budget only applies to
 * pre-first-byte failures (gateway connect, TLS, early "fetch
 * failed").
 */
export const MAX_PRESTREAM_ATTEMPTS = 3;

/**
 * Inactivity watchdog: abort the model stream if no token has arrived
 * for this long. Long transcripts can stall mid-stream when the
 * gateway holds the connection open but stops forwarding data.
 * 90 s is well above normal token-gap variance.
 */
export const STREAM_INACTIVITY_TIMEOUT_MS = 90_000;

/**
 * Threshold (in minutes of source video duration) above which the
 * article workflow switches from the single-pass LLM strategy to the
 * map-reduce strategy. Below the threshold a single LLM call writes
 * the whole article. At/above the threshold the transcript is sliced
 * into ~{@link SECTION_TARGET_WORDS}-word chunks, each generated by
 * its own bounded LLM call, then assembled. ~30 min single-pass is
 * reliably fine; 60+ min starts dropping connections; 45 min is a
 * comfortable margin. Tunable — no other code changes needed.
 */
export const MAP_REDUCE_THRESHOLD_MINUTES = 10;

/**
 * Target word count per section in the map-reduce strategy. Sections
 * snap to transcript-segment boundaries, so actual sizes vary ±20%.
 * ~2000 words ≈ 10–12 min of typical speech, which keeps each
 * per-section LLM call small enough to be reliable while limiting
 * fan-out for very long videos.
 */
export const SECTION_TARGET_WORDS = 2000;

/** Sanity cap on map-reduce sections. ~200 × 12 min ≈ 40 hours of source. */
export const MAX_SECTIONS = 200;

/**
 * Bound on simultaneous in-flight section generations in map-reduce.
 * Higher means faster wall-clock for very long videos but more risk
 * of tripping the gateway's per-minute token quota; 10 keeps a
 * 60-section video to ~6 batches.
 */
export const MAX_PARALLEL_SECTIONS = 10;

/**
 * Word count for fine-grained "windows" used by the map-reduce
 * topic-boundary detector. ~250 words ≈ 90 s of typical speech, which
 * is short enough to embed cleanly but large enough that a single
 * window's content represents a coherent micro-topic.
 */
export const EMBED_WINDOW_WORDS = 250;

/** Batch size for `embedMany` calls when embedding windows. */
export const EMBED_BATCH_SIZE = 100;

/**
 * Minimum and maximum word counts for a map-reduce section. The
 * topic-boundary detector greedily merges windows into sections,
 * cutting at high cosine-distance boundaries once min is reached and
 * force-cutting when max is hit. Together these bound the per-section
 * LLM call's input size while letting natural topic shifts shape
 * variable-length sections.
 */
export const MIN_SECTION_WORDS = 1000;
export const MAX_SECTION_WORDS = 4000;

/**
 * Cosine-distance threshold above which a window-pair boundary
 * counts as a topic shift. Picked for `text-embedding-3-small`:
 * within-topic adjacent windows typically sit at 0.1–0.3, across-topic
 * shifts at 0.4+. Tunable; raise to be more conservative (fewer cuts,
 * larger sections) or lower for finer-grained sections.
 */
export const TOPIC_BOUNDARY_DISTANCE = 0.4;
