export const MAIN_COLOR = '#515ada';
export const MINOR_COLOR = '#76ABDF';

export const TITLE = 'ReadTube';
export const GITHUB_REPO_URL = 'https://github.com/tuliren/readtube';
export const DESCRIPTION =
  'Turn YouTube subscriptions into a personal newsletter. Reclaim focus in a world engineered for distraction.';
export const DOMAIN = 'read.tube';
export const FULL_WEBSITE_URL = `https://www.${DOMAIN}`;
export const CONTACT_EMAIL = `contact@${DOMAIN}`;

// https://vercel.com/liren/~/ai-gateway/models
// google/gemini-3.1-flash-lite-preview: $0.25 / $1.5 - tend to summarize for article too
// openai/gpt-5.4-nano: $0.20 / $1.25 - not much formatting for article
// openai/gpt-5.4-mini: $0.74 / $4.5
// openai/gpt-5.4: $2.5 / $15 - too expensive
// anthropic/claude-haiku-4.5: $1 / $5 - slow
export const DEFAULT_AI_MODEL = 'openai/gpt-5.4-mini';

/**
 * Model for semantic embeddings. 1536 native dims matches the pgvector
 * column in the schema. We use OpenAI for embeddings even though
 * generation (summaries, articles, Ask-my-inbox answers) uses Google
 * Gemini — the Vercel AI Gateway routes them independently by provider
 * prefix, and no 1536-dim Google embedding model is available through
 * the gateway as a plain string identifier today. If you swap to a
 * model with a different output size, bump EMBEDDING_PROMPT_VERSION
 * AND alter the pgvector column + HNSW index together.
 *
 * https://developers.openai.com/api/docs/pricing
 * $0.02
 */
export const DEFAULT_EMBEDDING_MODEL = 'openai/text-embedding-3-small';

/**
 * Maximum attempts (initial + retries) for `streamText` calls in
 * generation steps when nothing has been streamed to the client yet.
 * Once any delta has been emitted, retrying would re-stream content
 * the client already received, so the retry budget only applies to
 * pre-first-byte failures (gateway connect, TLS, early "fetch
 * failed").
 */
export const MAX_PRESTREAM_ATTEMPTS = 3;

/**
 * Inactivity watchdog: abort the model stream if no token has arrived
 * for this long. Long transcripts can stall mid-stream when the
 * gateway holds the connection open but stops forwarding data.
 * 90 s is well above normal token-gap variance.
 */
export const STREAM_INACTIVITY_TIMEOUT_MS = 90_000;

/**
 * Threshold (in minutes of source video duration) above which the
 * article workflow switches from the single-pass LLM strategy to the
 * map-reduce strategy. Below the threshold a single LLM call writes
 * the whole article. At/above the threshold the transcript is sliced
 * into ~{@link SECTION_TARGET_WORDS}-word chunks, each generated by
 * its own bounded LLM call, then assembled. ~30 min single-pass is
 * reliably fine; 60+ min starts dropping connections; 45 min is a
 * comfortable margin. Tunable — no other code changes needed.
 */
export const MAP_REDUCE_THRESHOLD_MINUTES = 20;

/**
 * Target word count per section in the map-reduce strategy. Sections
 * snap to transcript-segment boundaries, so actual sizes vary in the
 * [0.5×, 2×] range around the target ({@link MIN_SECTION_WORDS} /
 * {@link MAX_SECTION_WORDS}). ~600 words ≈ 4 min of typical speech —
 * small enough that even a 10-min video produces multiple sections,
 * which is the whole point of the map-reduce path.
 */
export const SECTION_TARGET_WORDS = 600;

/**
 * Sanity cap on map-reduce sections. With a 600-word target, a 15hr
 * (~135 k word) video produces ~225 sections; the cap accommodates
 * that with a little headroom while still bounding pathological cases.
 */
export const MAX_SECTIONS = 300;

/**
 * Bound on simultaneous in-flight section generations in map-reduce.
 * Higher means faster wall-clock for very long videos but more risk
 * of tripping the gateway's per-minute token quota; 10 keeps a
 * 60-section video to ~6 batches.
 */
export const MAX_PARALLEL_SECTIONS = 10;

/**
 * Word count for fine-grained "windows" used by the map-reduce
 * topic-boundary detector. ~250 words ≈ 90 s of typical speech, which
 * is short enough to embed cleanly but large enough that a single
 * window's content represents a coherent micro-topic.
 */
export const EMBED_WINDOW_WORDS = 250;

/** Batch size for `embedMany` calls when embedding windows. */
export const EMBED_BATCH_SIZE = 100;

/**
 * Minimum and maximum word counts for a map-reduce section, derived
 * from {@link SECTION_TARGET_WORDS} so a single knob tunes sizing.
 * The topic-boundary detector cuts at high cosine-distance boundaries
 * once min is reached, and force-cuts at max regardless of semantic
 * signal — important for single-topic monologues / lectures where
 * adjacent windows never cross {@link TOPIC_BOUNDARY_DISTANCE}.
 *
 * 0.5× / 2× tolerance around the target gives sections that are
 * substantive enough not to fragment trivially, but never balloon to
 * the point where one section dominates the LLM context for the
 * map step.
 */
export const MIN_SECTION_WORDS = Math.floor(SECTION_TARGET_WORDS * 0.5);
export const MAX_SECTION_WORDS = SECTION_TARGET_WORDS * 2;

/**
 * Cosine-distance threshold above which a window-pair boundary
 * counts as a topic shift. Picked for `text-embedding-3-small`:
 * within-topic adjacent windows typically sit at 0.1–0.3, across-topic
 * shifts at 0.4+. Tunable; raise to be more conservative (fewer cuts,
 * larger sections) or lower for finer-grained sections.
 */
export const TOPIC_BOUNDARY_DISTANCE = 0.4;
