import { Minus, Plus } from 'lucide-react';
import { ReactNode } from 'react';

import { Container } from '@/components/Container';

const FAQS: { question: string; answer: ReactNode }[] = [
  {
    question: 'What platforms are supported?',
    answer: (
      <>
        <p>ReadTube ingests public video subtitles from:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>
            <span className="font-medium text-slate-700">YouTube</span>: videos, channels, and
            playlists
          </li>
          <li>
            <span className="font-medium text-slate-700">Bilibili</span>: videos and channels
          </li>
        </ul>
        <p>
          Paste any supported URL and we handle the rest: fetching subtitles, generating headlines,
          and turning long videos into readable articles.
        </p>
      </>
    ),
  },
  {
    question: 'What videos are not supported?',
    answer: (
      <>
        <p>A few kinds of videos don&apos;t fit ReadTube&apos;s reading-first model:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>
            <span className="font-medium text-slate-700">Short videos</span>. YouTube Shorts and
            other sub-minute clips are skipped. They&apos;re designed for quick visual viewing, and
            a transcript rarely adds much on top.
          </li>
          <li>
            <span className="font-medium text-slate-700">Videos without captions</span>. Music
            videos, silent footage, and anything the platform can&apos;t auto-caption have no
            transcript for us to read from.
          </li>
          <li>
            <span className="font-medium text-slate-700">Private or age-restricted videos</span>. We
            only fetch what&apos;s publicly accessible.
          </li>
        </ul>
      </>
    ),
  },
  {
    question: 'Who is ReadTube designed for?',
    answer:
      'Curious readers who subscribe to thoughtful creators (interviews, lectures, tech talks, essays) and want to consume them without the algorithmic pull of the feed. If you save videos for "later" and rarely return, ReadTube is for you.',
  },
  {
    question: 'Who is ReadTube not designed for?',
    answer:
      "If you mostly use YouTube for entertainment, vlogs, music, or visual content, ReadTube probably isn't the right fit. We leave out short videos, autoplay, and the recommendation feed on purpose, so the experience can feel quiet compared to a typical video app. It works best when you come for the ideas and want room to read and think.",
  },
  {
    question: 'How is this different from just watching at 2x speed?',
    answer: (
      <>
        <p>
          Reading is faster than listening, and reading with structure (headlines, summaries,
          timestamps) lets you skim, skip, and return. A 20-minute talk becomes a 5-minute read.
        </p>
        <p>
          More importantly, ReadTube turns your subscriptions into a searchable archive you can
          actually think with: highlight passages, pin notes, and search semantically across every
          channel you follow. A 2x playback speed can never give you that.
        </p>
      </>
    ),
  },
  {
    question: 'Do I need a YouTube or Bilibili account?',
    answer:
      'No. ReadTube is built on top of public video subtitles: no creator account, no importing your subscriptions. Add the channels you want to follow.',
  },
  {
    question: 'What happens to my notes and highlights?',
    answer:
      'Everything you highlight or annotate lives in your personal library. Notes are timestamped back to the source video, searchable across your whole archive, and yours to keep.',
  },
  {
    question: 'Does ReadTube work for videos without captions?',
    answer:
      'ReadTube relies on subtitles, either creator-provided or auto-generated by the platform. Most talks, interviews, and long-form content are covered. Music videos and silent footage are not a good fit.',
  },
  {
    question: 'Is there a free tier?',
    answer:
      'Yes. You can start reading for free and upgrade when your library outgrows casual use. Paid plans come with a 14-day free trial.',
  },
];

export default function Faq() {
  return (
    <section
      id="faq"
      aria-label="Frequently asked questions"
      className="bg-slate-50 py-24 sm:py-32"
    >
      <Container>
        <div className="mx-auto max-w-2xl text-center">
          <h2 className="font-display text-4xl font-medium tracking-tight text-slate-700 sm:text-5xl">
            Frequently asked questions
          </h2>
        </div>

        <ul className="mx-auto mt-16 max-w-3xl divide-y divide-slate-200 rounded-2xl border border-slate-200 bg-white shadow-sm">
          {FAQS.map((faq) => (
            <li key={faq.question}>
              <details className="group px-6 py-5 open:pb-6 sm:px-8">
                <summary className="flex cursor-pointer list-none items-start justify-between gap-6 text-left font-display text-lg font-medium text-slate-700 marker:hidden [&::-webkit-details-marker]:hidden">
                  <span>{faq.question}</span>
                  <span
                    aria-hidden
                    className="mt-1 flex h-6 w-6 flex-none items-center justify-center rounded-full text-slate-500 transition group-hover:text-slate-700"
                  >
                    <Plus className="h-4 w-4 group-open:hidden" />
                    <Minus className="hidden h-4 w-4 group-open:block" />
                  </span>
                </summary>
                <div className="flex flex-col gap-2.5 mt-4 text-base leading-relaxed text-slate-500">
                  {faq.answer}
                </div>
              </details>
            </li>
          ))}
        </ul>
      </Container>
    </section>
  );
}
