-- AlterTable
-- Two additive columns on Video. The autogenerated migration also tried
-- to drop/recreate the search_tsv GIN index and the VideoEmbedding HNSW
-- index because Prisma's diff doesn't understand the Unsupported(tsvector)
-- generated column or the raw-SQL ANN index from the inbox_foundation
-- migration. We strip those statements out by hand — they would break
-- search and recall on every deploy.
ALTER TABLE "Video"
    ADD COLUMN "duration_seconds" INTEGER,
    ADD COLUMN "transcript_unavailable" BOOLEAN NOT NULL DEFAULT false;
